### ISSUE TITLE
Setting 'United States' as measurement unit causes failure

### ISSUE THREAD

**Issue by james-malone** [braibaud/airthings-api#4]
Hello!

I installed this and tried it out and instantly the test sample failed in Python 3.8:

        james@defiant:~/airthings-crawler$ python3 test.py 
        Traceback (most recent call last):
          File "test.py", line 52, in <module>
            asyncio.run(test())
          File "/usr/lib/python3.8/asyncio/runners.py", line 43, in run
            return loop.run_until_complete(main)
          File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
            return future.result()
          File "test.py", line 17, in test
            me = await manager.get_me_instance()
          File "/home/james/.local/lib/python3.8/site-packages/airthings-api/api/web.py", line 84, in get_me_instance
            return mi.me_instance_from_dict(
          File "/home/james/.local/lib/python3.8/site-packages/airthings-api/responses/me_instance.py", line 201, in me_instance_from_dict
            return MeInstance.from_dict(s)
          File "/home/james/.local/lib/python3.8/site-packages/airthings-api/responses/me_instance.py", line 174, in from_dict
            notifications = Notifications.from_dict(obj.get("notifications"))
          File "/home/james/.local/lib/python3.8/site-packages/airthings-api/responses/me_instance.py", line 142, in from_dict
            thresholds = from_dict(Threshold.from_dict, obj.get("thresholds"))
          File "/home/james/.local/lib/python3.8/site-packages/airthings-api/responses/me_instance.py", line 54, in from_dict
            return { k: f(v) for (k, v) in x.items() }
          File "/home/james/.local/lib/python3.8/site-packages/airthings-api/responses/me_instance.py", line 54, in <dictcomp>
            return { k: f(v) for (k, v) in x.items() }
          File "/home/james/.local/lib/python3.8/site-packages/airthings-api/responses/me_instance.py", line 116, in from_dict
            default_high = from_int(obj.get("defaultHigh"))
          File "/home/james/.local/lib/python3.8/site-packages/airthings-api/responses/me_instance.py", line 38, in from_int
            assert isinstance(x, int) and not isinstance(x, bool)
        AssertionError
        Unclosed client session
        client_session: <aiohttp.client.ClientSession object at 0x7fd7381378b0>
        Unclosed connector
        connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7fd7370e3160>, 106130.569374508)]', '[(<aiohttp.client_proto.ResponseHandler object at 0x7fd73687f940>, 106130.954881909)]']
        connector: <aiohttp.connector.TCPConnector object at 0x7fd738137f70>

After looking at the stack trace, I noticed it came down to two checks on integers [here](https://github.com/braibaud/airthings-api/blob/c5d663fee58765786076e040131087897e4f55fd/airthings-api/responses/me_instance.py#L116) and [here](https://github.com/braibaud/airthings-api/blob/c5d663fee58765786076e040131087897e4f55fd/airthings-api/responses/me_instance.py#L117).
 
That seemed weird but after tinkering a bit, I noticed that if I changed my measurement units to metric, I could get a me instance back.  I am not sure why, but it looks like somehow the notification ranges vary based on the unit the user sets?

I will see if I can dig into this more. Also, thanks for doing this, it's really awesome and I value the work you put into this.

James

**Comment by james-malone** [comment]
It's the Radon measurement. In imperial it is a float but somewhere it's expected as an int.

**Comment by james-malone** [comment]
Alright, so I brutally fixed this by hot patching a fix to convert all thresholds to floats instead of expecting they will all be ints. 


In `locations_instance.py`:

    @dataclass
    class CurrentSensorValue:
        type_: str
        value: float
        provided_unit: str
        preferred_unit: str
        is_alert: bool
        thresholds: List[float]

          @staticmethod
          def from_dict(obj: Any) -> 'CurrentSensorValue':
              assert isinstance(obj, dict)
              type_ = from_str(obj.get("type"))
              value = from_float(obj.get("value"))
              provided_unit = from_str(obj.get("providedUnit"))
              preferred_unit = from_str(obj.get("preferredUnit"))
              is_alert = from_bool(obj.get("isAlert"))
              thresholds = from_list(from_float, obj.get("thresholds"))

This isn't a long term fix, but I also don't want to cut a disruptive PR. I am thinking that looking at the [measurement unit](https://github.com/braibaud/airthings-api/blob/master/airthings-api/responses/me_instance.py#L172) may be needed - floats for imperial, ints for metric.

**Comment by braibaud** [comment]
Hi, 
Thanks for all these investigations. I'll have a closer look; I have a new device which I connected to my hub so I was planning to retest anyway.
Maybe all measurements should be converted to float... Regardless of the measurement system.
Anyway, thanks for the feedback, much appreciated. If you want to submit a PR, please do so.
Thanks, Ben

**Comment by james-malone** [comment]
Hi Ben,

I just added a new Plus sensor and noticed a quick, which I wanted to mention if you're resetting, adding, or testing. Some measurements' thresholds are sent but the values are missing for the first 7 days. This is _probably_ unlikely to occur unless someone is using this and then adds a new sensor with something like a radon sensor. Here's an example return for my new Plus sensor:

`[{'type': 'radonShortTermAvg', 'providedUnit': 'pci', 'preferredUnit': 'pci', 'isAlert': False, 'thresholds': [2.7, 4]},`

I guess Airthings omits the value until it's calibrated. That appears to blow things up. 

James

**Comment by james-malone** [comment]
For posterity, I mended my new sensor issue (see above) with the following hot fix to `locations_instance.py`:

`value = from_float(obj.get("value")) if obj.get("value") else from_float(0.0)` for the method `def from_dict(obj: Any) -> 'CurrentSensorValue':`.

I didn't create a PR for this because I could see just reporting 0.0 to be controversial. :)

**Comment by braibaud** [comment]
> Hi Ben,
> 
> I just added a new Plus sensor and noticed a quick, which I wanted to mention if you're resetting, adding, or testing. Some measurements' thresholds are sent but the values are missing for the first 7 days. This is _probably_ unlikely to occur unless someone is using this and then adds a new sensor with something like a radon sensor. Here's an example return for my new Plus sensor:
> 
> `[{'type': 'radonShortTermAvg', 'providedUnit': 'pci', 'preferredUnit': 'pci', 'isAlert': False, 'thresholds': [2.7, 4]},`
> 
> I guess Airthings omits the value until it's calibrated. That appears to blow things up.
> 
> James

I think you're right, that might be due to the calibration. The radon sensor needs to accumulate data over a minimum period of time before being able to display an average value. The ideal solution is when we can support a `None` value for the `value` attribute, meaning the sensor isn't ready (yet):

``` python
@dataclass
class CurrentSensorValue:
    type_: str
    value: Optional[float]
    provided_unit: str
    preferred_unit: str
    is_alert: bool
    thresholds: List[float]

    @staticmethod
    def from_dict(obj: Any) -> 'CurrentSensorValue':
        assert isinstance(obj, dict)
        type_ = from_str(obj.get("type"))
        value = from_union([from_float, from_none], obj.get("value"))
        provided_unit = from_str(obj.get("providedUnit"))
        preferred_unit = from_str(obj.get("preferredUnit"))
        is_alert = from_bool(obj.get("isAlert"))
        thresholds = from_list(from_float, obj.get("thresholds"))
        return CurrentSensorValue(type_, value, provided_unit, preferred_unit, is_alert, thresholds)

    def to_dict(self) -> dict:
        result: dict = {}
        result["type"] = from_str(self.type_)
        result["value"] = from_union([from_float, from_none], self.value)
        result["providedUnit"] = from_str(self.provided_unit)
        result["preferredUnit"] = from_str(self.preferred_unit)
        result["isAlert"] = from_bool(self.is_alert)
        result["thresholds"] = from_list(from_float, self.thresholds)
        return result
```

what do you think?
Ben

**Comment by braibaud** [comment]
Clsoing the issue
